# Generated by Django 4.1 on 2022-08-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('New', 'New')], max_length=200),
        ),
    ]
