# Generated by Django 4.1 on 2022-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_alter_queue_queue_id_alter_queue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Active', 'Active')], max_length=200),
        ),
        migrations.AlterField(
            model_name='queue',
            name='type',
            field=models.CharField(choices=[('hardware', 'Hardware Issue'), ('software', 'Software Issue'), ('phone', 'Phone Issue'), ('other', 'Account Issue')], max_length=200),
        ),
    ]
